name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: zo-ly/wakatime-charts@master
        with:
          BRANCH_NAME: main
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
